name: Manual Workflow

# 수동 트리거 설정/on되면 실행
on:
  workflow_dispatch:

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello from GitHub Actions, fantastic world!"
      
      - name: Show current time 
        run: date

      - name: show system information
        run: uname -a

      - name: Multiple commands
        run: |
         ls -la
         python -v
         echo "Running multiple commands"
         echo "Current date and time: $(date)"
         echo "fantastic world"
      
